// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD5zrp-BiCViO2aC2NPbtay8KTzVueXUo',
    appId: '1:409906904854:web:a2284cb1f618e64f8b9a37',
    messagingSenderId: '409906904854',
    projectId: 'autoparts-f9909',
    authDomain: 'autoparts-f9909.firebaseapp.com',
    storageBucket: 'autoparts-f9909.appspot.com',
    measurementId: 'G-FM1KLJEET5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrz6UsQn1eChrerJ-lGC8AdQmymkELz5E',
    appId: '1:409906904854:android:50c384f3a63942b08b9a37',
    messagingSenderId: '409906904854',
    projectId: 'autoparts-f9909',
    storageBucket: 'autoparts-f9909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqY8qJbrmtlWlTMaNgvD_l_p4BambIm4w',
    appId: '1:409906904854:ios:ee7c70d47043e2b68b9a37',
    messagingSenderId: '409906904854',
    projectId: 'autoparts-f9909',
    storageBucket: 'autoparts-f9909.appspot.com',
    iosClientId: '409906904854-08m3r050fba65igtakknvs5psnlsn370.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoparts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqY8qJbrmtlWlTMaNgvD_l_p4BambIm4w',
    appId: '1:409906904854:ios:ee7c70d47043e2b68b9a37',
    messagingSenderId: '409906904854',
    projectId: 'autoparts-f9909',
    storageBucket: 'autoparts-f9909.appspot.com',
    iosClientId: '409906904854-08m3r050fba65igtakknvs5psnlsn370.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoparts',
  );
}
